### ISSUE TITLE
Menu Disappears in Medium Width Mode

### ISSUE THREAD

**Issue by chrisblack** [wet-boew/cdts-sgdc#547] opened 2022-06-21 14:07 UTC
Steps to Re-produce:
1. Go to https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html
2. Maximize window and top menu bar display as a series of button links.
3. Snap window to half screen width, which causes the top-menu to disappear.
4. Shrink the window width smaller than half the screen resolution and the menu re-appears as a drop-down.

Screen resolution:  1920 X 1200
OS: Windows 11 and Windows 10

Here's an image of the screen without the menu:
![image](https://user-images.githubusercontent.com/2004685/174819112-3d6f0c22-ca40-4a43-b01c-4cd679637a1b.png)

Any suggestions on how to get the menu to display in medium width mode would be greatly appreciated.

**Comment by ahmad-shahid** [comment] 2022-06-29 14:44
Hello, the problem is now fixed. The menu should still be visible for a medium width. 
Thank you!

**Comment by chrisblack** [comment] 2022-06-29 15:40
Hello, I just checked and the menu isn't showing for medium width:
![image](https://user-images.githubusercontent.com/2004685/176478144-9b6efbc1-0c49-4d9d-81a1-f81d8a329ef9.png)

**Comment by ahmad-shahid** [comment] 2022-06-29 19:36
This is strange because it looks good on my end and I just had it verified by my team. Can you try to hard refresh your page and try again?

**Closed** 2023-01-04 18:27 UTC
