### ISSUE TITLE
Removal of SRI for jQuery scripts

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#84] opened 2020-02-07 19:05 UTC
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/78

@shawnthompson created this issue

We are having issues with jQuery and the SRI SHA. So I removed them for now when I updated the jQuery versions to match WET. I will add them back once we figure out the issue.

**Comment by nicolasraymond** [comment] 2020-02-20 20:57
ffff

**Comment by nicolasraymond** [comment] 2020-02-20 21:00
A little history about removal of the SRI.

The issue is here:

https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/78

What was happening is that something what changing the line ending when we would be moving it to Canada.ca and the hashes wouldn’t be the same.

Pierre fixed this and I will test it, why I write this email.

I will test it for you. How I’ll be doing this if I got to the Canada.ca server and load the javascript that was uploaded in my browser:

https://www.canada.ca/etc/designs/canada/cdts/gcweb/rn/cdts/compiled/wet-en.js

I save the file to the ServiceCanada/gcci-design-cdts.git repo that was used to push this to the server. This way git will show any changes. Before it used to show a modification and on the file but didn’t show any exactly, because the only change was the End of Line.

I just did the same thing with the latest files I pushed and it’s not showing any changes. I think we should be good to add the SRI back to the files.

Shawn Thompson 
Conseiller technique en accessibilité Web | Web Accessibility Technical Advisor
Accessibilité TI / DGIIT | IT Accessibility / IITB
Email | Courriel Shawn.Thompson@hrsdc-rhdcc.gc.ca
Telephone | Téléphone 438-892-1834
Government of Canada | Gouvernement du Canada

From: Dubois, Pierre P [NC] <pierre.dubois@servicecanada.gc.ca> 
Sent: February 6, 2020 3:28 PM
To: NC-SGDC-CDTS-GD <NC-SGDC-CDTS-GD@hrsdc-rhdcc.gc.ca>
Cc: Thompson, Shawn S [NC] <shawn.thompson@hrsdc-rhdcc.gc.ca>
Subject: Use Sub Ressource Integrity in CDTS

Hi Folk,

When you have a moment, we would need to talk about how we can use SRI. This is to improve the security of the software

At your convenience, you can give me a call 819-271-6373 or I can setup a webex conference. 

Thank you



Pierre Dubois

Gestionnaire du dévelopment de Canada.ca et Gestionnaire de projet de la boîte à outils de l’expérience web, Éditeur principal
Service Canada / Gouvernement du Canada
pierre.dubois@servicecanada.gc.ca / 819-271-6373

Canada.ca Developer Lead and Web Experience Toolkit Project Lead, Principal Publisher
Service Canada / Government of Canada
pierre.dubois@servicecanada.gc.ca / 819-271-6373

**Comment by patricehernert** [comment] 2020-12-21 16:40
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Closed** 2021-08-30 18:42 UTC
Labels: bug, email-related
